#!/bin/bash

set -e;
source scripts/set-env

## Wrap-N-Zap deploy
cp -r repos/wrap-n-zap deploys/
cp hardhat.config.js deploys/wrap-n-zap/
cp scripts/deployScripts/deployWrapNZap.js deploys/wrap-n-zap/

cd ../wrap-n-zap
rm -rf node_modules
npm i
echo >> ../../deploy.$1.md
echo "## Deploying Wrap N Zap  "  >> ../../deploy.$1.md
echo '```  '  >> ../../deploy.$1.md
npx hardhat run deployWrapNZap.js --network $1 >> ../../deploy.$1.md
echo '```  '  >> ../../deploy.$1.md
