#!/bin/bash

set -e;
source scripts/set-env

## NiftyMInionSummoner deploy
cp -r repos/NiftyMInionSummoner deploys/
## copy the necessary scripts and package environments
cp repos/wrap-n-zap/package.json deploys/NiftyMInionSummoner/
cp scripts/deployScripts/deployNiftyMinionSummoner.js deploys/NiftyMInionSummoner/

cd ../NiftyMInionSummoner
npm i
echo >> ../../deploy.$1.md
echo "## Deploying Nifty Minion  "   >> ../../deploy.$1.md
echo '```  '  >> ../../deploy.$1.md
npx hardhat run deployNiftyMinionSummoner.js --network $1 >> ../../deploy.$1.md
echo '```  '  >> ../../deploy.$1.md
