#!/bin/bash

set -e;
source scripts/set-env

## Prepare the environment
rm -rf deploys/
mkdir -p deploys

## copy the repos with compiled contracts into our deploys directory for staging and deployment
## Molochv2 deploy
cp -r repos/Molochv2.1 deploys/
## copy the necessary scripts and package environments
cp repos/wrap-n-zap/package.json deploys/Molochv2.1/
cp scripts/deployScripts/deployMolochv2.1.js ./deploys/Molochv2.1

## NiftyMInionSummoner deploy
cp -r repos/NiftyMInionSummoner deploys/
## copy the necessary scripts and package environments
cp repos/wrap-n-zap/package.json deploys/NiftyMInionSummoner/
cp scripts/deployScripts/deployNiftyMinionSummoner.js deploys/NiftyMInionSummoner/

## Wrap-N-Zap deploy
cp -r repos/wrap-n-zap deploys/
cp hardhat.config.js deploys/wrap-n-zap/
cp scripts/deployScripts/deployWrapNZap.js deploys/wrap-n-zap/


### Start to deploy
cd deploys/Molochv2.1
npm i
echo "## Deploying Molochv2.1  "  > ../../deploy.testnet.md
echo '```  '  >> ../../deploy.testnet.md
npx hardhat run deployMolochv2.1.js --network harmonyTest >> ../../deploy.testnet.md
echo '```  '  >> ../../deploy.testnet.md

cd ../NiftyMInionSummoner
npm i
echo >> ../../deploy.testnet.md
echo "## Deploying Nifty Minion  "   >> ../../deploy.testnet.md
echo '```  '  >> ../../deploy.testnet.md
npx hardhat run deployNiftyMinionSummoner.js --network harmonyTest >> ../../deploy.testnet.md
echo '```  '  >> ../../deploy.testnet.md

cd ../wrap-n-zap
rm -rf node_modules
npm i
echo >> ../../deploy.testnet.md
echo "## Deploying Wrap N Zap  "  >> ../../deploy.testnet.md
echo '```  '  >> ../../deploy.testnet.md
npx hardhat run deployWrapNZap.js --network harmonyTest >> ../../deploy.testnet.md
echo '```  '  >> ../../deploy.testnet.md
