#!/bin/bash

set -e;
source scripts/set-env
export OUTPUT_FILE=deploy.$1.md

echo $OUTPUT_FILE

## Prepare the environment
rm -rf deploys/
mkdir -p deploys

## copy the repos with compiled contracts into our deploys directory for staging and deployment
## Molochv2 deploy
cp -r repos/MinionSummoner deploys/
## copy the necessary scripts and package environments
cp repos/wrap-n-zap/package.json deploys/MinionSummoner/
cp scripts/deployScripts/deployMolochv1.js ./deploys/MinionSummoner


## Molochv2 deploy
cp -r repos/Molochv2.1 deploys/
## copy the necessary scripts and package environments
cp repos/wrap-n-zap/package.json deploys/Molochv2.1/
cp scripts/deployScripts/deployMolochv2.1.js ./deploys/Molochv2.1



## NiftyMInionSummoner deploy
cp -r repos/NiftyMInionSummoner deploys/
## copy the necessary scripts and package environments
cp repos/wrap-n-zap/package.json deploys/NiftyMInionSummoner/
cp scripts/deployScripts/deployNiftyMinionSummoner.js deploys/NiftyMInionSummoner/

## Wrap-N-Zap deploy
cp -r repos/wrap-n-zap deploys/
cp hardhat.config.js deploys/wrap-n-zap/
cp scripts/deployScripts/deployWrapNZap.js deploys/wrap-n-zap/


### Start to deploy
cd deploys/Molochv2.1
npm i
echo "## Deploying Molochv2.1  "  > ../../$OUTPUT_FILE
echo '```  '  >> ../../$OUTPUT_FILE
npx hardhat run deployMolochv2.1.js --network $1 >> ../../$OUTPUT_FILE
echo '```  '  >> ../../$OUTPUT_FILE

cd ../MinionSummoner
npm i
echo "## Deploying Molochv1  "  >> ../../$OUTPUT_FILE
echo '```  '  >> ../../$OUTPUT_FILE
npx hardhat run deployMolochv1.js --network $1 >> ../../$OUTPUT_FILE
echo '```  '  >> ../../$OUTPUT_FILE

cd ../NiftyMInionSummoner
npm i
echo >> ../../$OUTPUT_FILE
echo "## Deploying Nifty Minion  "   >> ../../$OUTPUT_FILE
echo '```  '  >> ../../$OUTPUT_FILE
npx hardhat run deployNiftyMinionSummoner.js --network $1 >> ../../$OUTPUT_FILE
echo '```  '  >> ../../$OUTPUT_FILE

cd ../wrap-n-zap
rm -rf node_modules
npm i
echo >> ../../$OUTPUT_FILE
echo "## Deploying Wrap N Zap  "  >> ../../$OUTPUT_FILE
echo '```  '  >> ../../$OUTPUT_FILE
npx hardhat run deployWrapNZap.js --network $1 >> ../../$OUTPUT_FILE
echo '```  '  >> ../../$OUTPUT_FILE
